### ISSUE TITLE
Continous integration support

### ISSUE THREAD

**Issue by jntakpe** [SopraSteriaGroup/initiatives_backend_ideas#10]
Intégrer un moteur d'intégration continue (certainnement TravisCI)

**Comment by rjansem** [comment]
Et avec Travis ci on pourra déployer autre part que sur heroku ?

**Comment by jntakpe** [comment]
Je sais pas mais à minima ça build le projet et ça exécute les tests

**Comment by jntakpe** [comment]
@rjansem Oui avec travisci tu peux déployer à peu près partout
